# Generated by Django 5.2 on 2025-06-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
