# Generated by Django 5.2 on 2025-06-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_review_approved_remove_review_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
