# Generated by Django 5.2 on 2025-06-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
