# Generated by Django 5.2 on 2025-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
